[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.20"
evm_version = "shanghai"

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@tokenized-strategy/=lib/tokenized-strategy/src/",
    "@periphery/=lib/tokenized-strategy-periphery/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
]

[fuzz]
runs = 1000
max_test_rejects = 1_000_000

