[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = "0.8.25"
bytecode_hash = "none"
cbor_metadata = false
sparse_mode = false
via_ir = true
optimizer = true
optimizer_runs = 1_000_000

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/",
    "@tokenized-strategy/=lib/tokenized-strategy/src/",
    "@periphery/=lib/tokenized-strategy-periphery/src/",
    "@ethena-assets/=lib/ethena-assets/contracts/contracts/",
]

[profile.default.optimizer_details]
constantOptimizer = true
yul = true

[profile.default.optimizer_details.yulDetails]
stackAllocation = true

[fuzz]
runs = 1000
max_test_rejects = 1_000_000

